
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: <%= ENV.fetch("SUPER_SECRET") %>

development:
  <<: *default
  database: vcypherdev

test:
  <<: *default
  database: vcyphertest

production:
  <<: *default
  database: vcypherprod